# Generated by Django 4.0.1 on 2022-02-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
